# Form implementation generated from reading ui file 'main_qt6.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 436)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 60, 581, 321))
        self.calendarWidget.setObjectName("calendarWidget")
        self.lineEdit_search = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_search.setGeometry(QtCore.QRect(650, 60, 311, 22))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.groupBox_main_variants = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_main_variants.setGeometry(QtCore.QRect(10, 0, 241, 41))
        self.groupBox_main_variants.setObjectName("groupBox_main_variants")
        self.radioButton_birthday = QtWidgets.QRadioButton(parent=self.groupBox_main_variants)
        self.radioButton_birthday.setGeometry(QtCore.QRect(100, 20, 131, 20))
        self.radioButton_birthday.setObjectName("radioButton_birthday")
        self.radioButton_tasks = QtWidgets.QRadioButton(parent=self.groupBox_main_variants)
        self.radioButton_tasks.setGeometry(QtCore.QRect(10, 20, 71, 20))
        self.radioButton_tasks.setChecked(True)
        self.radioButton_tasks.setObjectName("radioButton_tasks")
        self.groupBox_search_kinds = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_search_kinds.setGeometry(QtCore.QRect(630, 0, 341, 51))
        self.groupBox_search_kinds.setObjectName("groupBox_search_kinds")
        self.radioButton_search_curr_list = QtWidgets.QRadioButton(parent=self.groupBox_search_kinds)
        self.radioButton_search_curr_list.setGeometry(QtCore.QRect(10, 20, 171, 20))
        self.radioButton_search_curr_list.setChecked(True)
        self.radioButton_search_curr_list.setObjectName("radioButton_search_curr_list")
        self.radioButton_search_global_list = QtWidgets.QRadioButton(parent=self.groupBox_search_kinds)
        self.radioButton_search_global_list.setGeometry(QtCore.QRect(200, 20, 121, 20))
        self.radioButton_search_global_list.setObjectName("radioButton_search_global_list")
        self.tableView_search_result = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView_search_result.setGeometry(QtCore.QRect(610, 100, 371, 281))
        self.tableView_search_result.setObjectName("tableView_search_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1001, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ежедневник"))
        self.groupBox_main_variants.setTitle(_translate("MainWindow", "Выбор темы"))
        self.radioButton_birthday.setText(_translate("MainWindow", "Дни Рождения"))
        self.radioButton_tasks.setText(_translate("MainWindow", "Задачи"))
        self.groupBox_search_kinds.setTitle(_translate("MainWindow", "Выбор варианта поиска"))
        self.radioButton_search_curr_list.setText(_translate("MainWindow", "Поиск из текущего списка"))
        self.radioButton_search_global_list.setText(_translate("MainWindow", "Поиск глобально"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
